version: "3.9"

services:

  postgresDB:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "ePTgu5CTBA9QkGjBq28z"
      POSTGRES_USER: "DoctorAppointmentAppAdmin"
      POSTGRES_DB: "DoctorAppointmentApp"