CREATE TABLE IF NOT EXISTS DOCTORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DOCTOR_SPECIALITY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PATIENTS
(
    ID           BIGSERIAL NOT NULL  PRIMARY KEY,
    FIRST_NAME   VARCHAR(255),
    LAST_NAME    VARCHAR(255),
    AGE          INTEGER,
    PHONE_NUMBER VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS APPOINTMENTS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    DOCTOR_ID BIGINT,
    PATIENT_ID BIGINT,
    REGISTER_DATE timestamp,
    APPOINTMENT_DATE timestamp,
    ADDITIONAL_INFORMATION VARCHAR(255),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(ID)
);




